ARG PYTHON_VERSION=2
FROM python:${PYTHON_VERSION}-alpine

LABEL service=nginx-ldap-login

COPY nginx-ldap-login.py /usr/src/app/
COPY login-page/ /usr/src/app/login-page/

WORKDIR /usr/src/app/

RUN apk update && apk add bash

SHELL ["/bin/bash", "-c"]

RUN /bin/bash -c "[[ $PYTHON_VERSION == 2* ]] && apk --no-cache add python-dev || apk --no-cache add python3-dev"

# Install required software
RUN \
    apk --no-cache add openldap-dev && \
    apk --no-cache add --virtual build-dependencies build-base && \
    apk --no-cache add gcc musl-dev libffi-dev openssl-dev && \
    pip install --upgrade pip &&\
    pip install python-dotenv setuptools_rust cryptography && \
    apk del build-dependencies

EXPOSE 9000

CMD ["python", "/usr/src/app/nginx-ldap-login.py"]
