ARG PYTHON_VERSION=2
FROM python:${PYTHON_VERSION}-alpine

LABEL service=nginx-ldap-auth

COPY nginx-ldap-auth.py /usr/src/app/

WORKDIR /usr/src/app/

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tencent.com/g' /etc/apk/repositories

RUN apk update && apk add bash

SHELL ["/bin/bash", "-c"]

RUN /bin/bash -c "[[ $PYTHON_VERSION == 2* ]] && apk --no-cache add python-dev || apk --no-cache add python3-dev"

# Install required software
RUN \
    apk --no-cache add openldap-dev && \
    apk --no-cache add --virtual build-dependencies build-base && \
    apk --no-cache add gcc musl-dev libffi-dev openssl-dev && \
    pip install -i https://mirrors.tencent.com/pypi/simple/ --upgrade pip &&\
    pip install -i https://mirrors.tencent.com/pypi/simple/ python-ldap python-dotenv setuptools_rust cryptography && \
    apk del build-dependencies

EXPOSE 8888

CMD ["python", "/usr/src/app/nginx-ldap-auth.py", "--host", "0.0.0.0", "--port", "8888"]
